// User/web3
export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT'
export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS'
export const RECEIVE_HAS_WEB3 = 'RECEIVE_HAS_WEB3'
export const RECEIVE_IS_CONNECTED = 'RECEIVE_IS_CONNECTED'
export const RECEIVE_ACCOUNT_UNLOCKED = 'RECEIVE_ACCOUNT_UNLOCKED'
export const RECEIVE_COINBASE = 'RECEIVE_COINBASE'
export const RECEIVE_ACCOUNT_TRANSACTIONS = 'RECEIVE_ACCOUNT_TRANSACTIONS'
export const RECEIVE_USER_NOT_AUTHENTICATED = 'RECEIVE_USER_NOT_AUTHENTICATED'
export const RECEIVE_USER_NUM_DID = 'RECEIVE_USER_NUM_DID'
export const RECEIVE_TOTAL_SUPPLY_DID = 'RECEIVE_TOTAL_SUPPLY_DID'
export const RECEIVE_NETWORK_ID = 'RECEIVE_NETWORK_ID'
export const RECEIVE_USER_NUM_ETHER = 'RECEIVE_USER_NUM_ETHER'

// Tasks
export const REQUEST_TASKS = 'REQUEST_TASKS'
export const RECEIVE_TASKS = 'RECEIVE_TASKS'
export const REQUEST_TASK = 'REQUEST_TASK'
export const RECEIVE_TASK = 'RECEIVE_TASK'
export const SELECT_TASK = 'SELECT_TASK'
export const SUBMIT_TASK = 'SUBMIT_TASK'
export const SET_NUM_TASKS = 'SET_NUM_TASKS'
export const REQUEST_TASKS_INSTANCE = 'REQUEST_TASKS_INSTANCE'
export const RECEIVE_TASKS_INSTANCE = 'RECEIVE_TASKS_INSTANCE'
export const SUBMIT_REWARD_VOTE = 'SUBMIT_REWARD_VOTE'

//  PullRequests
export const REQUEST_PULLREQUESTS = 'REQUEST_PULLREQUESTS'
export const RECEIVE_PULLREQUESTS = 'RECEIVE_PULLREQUESTS'
export const REQUEST_PULLREQUEST = 'REQUEST_PULLREQUEST'
export const RECEIVE_PULLREQUEST = 'RECEIVE_PULLREQUEST'
export const SUBMIT_PULLREQUEST = 'SUBMIT_PULLREQUEST'
export const REQUEST_PULLREQUESTS_INSTANCE = 'REQUEST_PULLREQUESTS_INSTANCE'
export const RECEIVE_PULLREQUESTS_INSTANCE = 'RECEIVE_PULLREQUESTS_INSTANCE'
export const SET_NUM_PULLREQUESTS = 'SET_NUM_PULLREQUESTS'

//  IPFS
export const REQUEST_IPFS_NODE = 'REQUEST_IPFS_NODE'
export const RECEIVE_IPFS_NODE = 'RECEIVE_IPFS_NODE'
export const SUBMIT_IPFS_HASH = 'SUBMIT_IPFS_HASH'
export const REQUEST_IPFS_HASH = 'REQUEST_IPFS_HASH'
export const RECEIVE_IPFS_HASH = 'export const RECEIVE_IPFS_HASH'

// Status
export const SET_DEFAULT_STATUS = 'SET_DEFAULT_STATUS'
export const SET_STATUS_MESSAGE = 'SET_STATUS_MESSAGE'

// Parameters
export const REQUEST_PARAMETERS = 'REQUEST_PARAMETERS'
export const RECEIVE_PARAMETERS = 'RECEIVE_PARAMETERS'
export const RECEIVE_EVENT = 'RECEIVE_EVENT'

//  Faucet
export const SUBMIT_FAUCET_REQUEST = 'SUBMIT_FAUCET_REQUEST'
