//  Accounts
export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS'
export const SELECT_ADDRESS = 'SELECT_ADDRESS'
export const REQUEST_WEB3_DATUM = 'REQUEST_WEB3_DATUM'
export const RECEIVE_WEB3_DATUM = 'RECEIVE_WEB3_DATUM'
export const RECEIVE_ACCOUNT_DATUM = 'RECEIVE_ACCOUNT_DATUM'
export const REQUEST_ACCOUNT_DATUM = 'REQUEST_ACCOUNT_DATUM'
export const RECEIVE_HAS_WEB3 = 'RECEIVE_HAS_WEB3'
export const RECEIVE_IS_CONNECTED = 'RECEIVE_IS_CONNECTED'

// Tasks
export const REQUEST_TASKS = 'REQUEST_TASKS'
export const RECEIVE_TASKS = 'RECEIVE_TASKS'
export const REQUEST_TASK = 'REQUEST_TASK'
export const RECEIVE_TASK = 'RECEIVE_TASK'
export const SELECT_TASK = 'SELECT_TASK'
export const SUBMIT_TASK = 'SUBMIT_TASK'
export const SET_NUM_TASKS = 'SET_NUM_TASKS'
export const REQUEST_TASKS_INSTANCE = 'REQUEST_TASKS_INSTANCE'
export const RECEIVE_TASKS_INSTANCE = 'RECEIVE_TASKS_INSTANCE'

//  PullRequests
export const REQUEST_PULLREQUESTS = 'REQUEST_PULLREQUESTS'
export const RECEIVE_PULLREQUESTS = 'RECEIVE_PULLREQUESTS'
export const REQUEST_PULLREQUEST = 'REQUEST_PULLREQUEST'
export const RECEIVE_PULLREQUEST = 'RECEIVE_PULLREQUEST'
export const SUBMIT_PULLREQUEST = 'SUBMIT_PULLREQUEST'
export const REQUEST_PULLREQUESTS_INSTANCE = 'REQUEST_PULLREQUESTS_INSTANCE'
export const RECEIVE_PULLREQUESTS_INSTANCE = 'RECEIVE_PULLREQUESTS_INSTANCE'
export const SET_NUM_PULLREQUESTS = 'SET_NUM_PULLREQUESTS'

//  IPFS
export const REQUEST_IPFS_NODE = 'REQUEST_IPFS_NODE'
export const RECEIVE_IPFS_NODE = 'RECEIVE_IPFS_NODE'
export const SUBMIT_IPFS_HASH = 'SUBMIT_IPFS_HASH'
export const REQUEST_IPFS_HASH = 'REQUEST_IPFS_HASH'
export const RECEIVE_IPFS_HASH = 'export const RECEIVE_IPFS_HASH'

// Status
export const SET_DEFAULT_STATUS = 'SET_DEFAULT_STATUS'
export const CONFIRM_BLOCKCHAIN_ADDITION = 'CONFIRM_BLOCKCHAIN_ADDITION'
export const SET_AVG_BLOCKTIME = 'SET_AVG_BLOCKTIME'
