#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

ETH_ADDRESS=$(git config user.ethAddress)
if [[ -z ${ETH_ADDRESS} ]]; then
  echo "WARNING\nIt looks like you are trying to commit to a Distense repo without 'user.ethAddress' set in your git config."
  echo "If you'd like to receive a reward for your contribution set 'git config user.ethAddress."
  echo "If you don't have an Ethereum address, please google how you may easiestly find one."
  echo "To bypass this message try your commit again with: --no-verify"
  exit 1
fi
